Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "localhost", auto_correct: true
  config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.synced_folder "clinic", "/home/clinic"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update
    sudo yum -y install epel-release
    sudo rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    yum install --enablerepo=remi,remi-php71 php php-devel php-mbstring php-pdo php-gd php-xml php-mcrypt -y php --version  
    SHELL
end